### ISSUE TITLE
Clicking "Share an Invite Link with Your Friend" will then invite the next person to visit the site to play with you

### ISSUE THREAD

**Issue by darrenlevy** [yoav-zibin/default-theme#3] opened 2016-03-13 17:23 UTC

**Comment by yoav-zibin** [comment] 2016-03-13 18:38
So it's a feature request I guess (not a bug :))

There is no "site", only app. We now use a site for testing purposes, but the end-user only uses the app (not our website).
So closing this feature request :)

**Closed by yoav-zibin** 2016-03-13 18:38 UTC

**Comment by darrenlevy** [comment] 2016-03-13 19:32
I'm pretty sure this is a bug, sorry for not explaining clearly enough the first time.
Steps to reproduce:
1) Visit here and log in with Facebook:
http://www.multiplayer-gaming.com/v1/dist/#/main
2) Click New Game
3) Click "Share an Invite Link with your Friends"
4) Immediately, open an Incognito Window and visit here:
http://www.multiplayer-gaming.com/v1/dist/#/main
5) Click Close
6) See that you were invited by the Facebook version of yourself to a new game.

Assert True:
Clicking "Share an Invite Link with your Friends" should not invite the next random player to a game.

**Comment by yoav-zibin** [comment] 2016-03-13 22:52
I explained that it works using IP address, so it's working as intended.
Read more about deep linking :)

**Comment by darrenlevy** [comment] 2016-03-13 23:45
Ah, very cool!
